### PR TITLE
Provide previous behavior of TS_EXEC_CALC_NOT via TS_EXEC_SKIP_NOT

### PR DESCRIPTION
**Pull request by feld**
Addresses #88 

This flag may not be needed at all on >=130000. Please carefully verify.

https://www.mail-archive.com/pgsql-committers@lists.postgresql.org/msg14157.html

### CODE REVIEW

**Comment by ololobus** [comment]
Hi @feld, could you please rebase your branch on top of the current `master`? in order we were able to check it again/ run tests and merge

**Comment by feld** [comment]
Ok, I think this solves the conflict issue. Note, I see that there was a commit added to this MR by @feodor from the branch `svace-fix` commit b1c8e895308bdeb5454f975eeea60eec8b55e90b which I did not include. If that is something that should survive and be included in this MR please re-add it.

**Comment by ololobus** [comment]
Thanks! It was not actually added **by him to your branch**, it happened because I have force-pushed master from our GitLab repo in order to synchronise these two repos. And this commit was only left in you branch. In short, you did everything right :)

**Comment by pashkinelfe** [comment]
RUM now uses a private version rum_ts_execute() and TS_EXEC_CALC_NOT is now defined in the right meaning for calls of rum_ts_execute(). Right usage of TS_EXEC_CALC_NOT is described in the comments in rum_ts_utils.c

**Pull request closed without merging**
